version: 2
updates:

  # yarn deps on typescript dev branch
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev/typescript"
    # Disable PRs for yarn dependencies
    open-pull-requests-limit: 0
